sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

language: scala
scala:
  - 2.12.1
  - 2.11.8
jdk:
  - oraclejdk8
before_script:
- psql -c "CREATE ROLE sa WITH SUPERUSER LOGIN PASSWORD 'sa';" -U postgres
- psql -c "CREATE DATABASE scalikejdbc;" -U postgres
- mysql -e 'GRANT ALL ON *.* TO sa@"localhost"IDENTIFIED BY "sa";FLUSH PRIVILEGES;' -uroot
- mysql -e "CREATE DATABASE scalikejdbc;" -usa -psa
script:
- cp src/test/resources/jdbc_$SCALIKEJDBC_DATABASE.properties src/test/resources/jdbc.properties
- sbt ++${TRAVIS_SCALA_VERSION} test
env:
  matrix:
    - SCALIKEJDBC_DATABASE="mysql"
    - SCALIKEJDBC_DATABASE="postgresql"
    - SCALIKEJDBC_DATABASE="h2"
    - SCALIKEJDBC_DATABASE="hsqldb"
